# SPDX-FileCopyrightText: 2026 Donnish Pty Ltd
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Scheduler tests — the cross-platform install paths.

Only one of the three platforms can be exercised on any given machine, so the
other two ship on faith unless something checks the artefacts they generate.
These build the launchd plist, the systemd units and the schtasks command
without installing anything, and assert the properties that would break a user
silently: wrong cadence, missing working directory, a resident process where a
periodic one was intended.

Nothing here calls launchctl, systemctl or schtasks.
"""

import plistlib
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import scheduler  # noqa: E402

# No test may reach the internet: a call that a swallowing error handler hides
# passes for the wrong reason, and this suite mentions the poll path. See
# tests/netguard.py -- one suite run was making 25 real requests before this.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from netguard import (  # noqa: E402
    block_outbound_for_module, restore_outbound_for_module)

# Tests must never write into the developer's own ~/.airo (CONVENTIONS).
# poller's paths are module-level and resolved at import, so any test reaching
# code that calls log() writes to the real file unless they are redirected.
# A suite run appended two fixture strings to a live install's log, between two
# real polls, and the maintainer reasonably read that as their monitor dying.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from homeguard import (  # noqa: E402
    REAL_AIRO_HOME, redirect_airo_paths_for_module,
    restore_airo_paths_for_module)

# No test may reach the session manager this machine is logged in to. The
# stubs below replace `scheduler.run` per test case so the argv can be
# asserted on; this is the floor underneath them, at the subprocess seam, for
# the paths no stub covers -- including the tests that deliberately restore
# the real HOME to check the ordinary case is not refused. See
# tests/schedguard.py: this suite is the one that unloaded the developer's own
# launchd agent.
import schedguard  # noqa: E402
from schedguard import (  # noqa: E402
    block_session_managers_for_module, restore_session_managers_for_module)


def setUpModule():
    redirect_airo_paths_for_module()
    block_outbound_for_module()
    block_session_managers_for_module()


def tearDownModule():
    restore_session_managers_for_module()
    restore_airo_paths_for_module()
    restore_outbound_for_module()



class TestPlatformDetection(unittest.TestCase):
    def test_detects_one_of_three(self):
        self.assertIn(scheduler.system(), ("macos", "linux", "windows"))

    def test_every_platform_has_a_full_backend(self):
        """A platform missing an entry raises KeyError at install time, which
        is a crash rather than a message."""
        for plat in ("macos", "linux", "windows"):
            self.assertIn(plat, scheduler.BACKENDS)
            self.assertEqual(len(scheduler.BACKENDS[plat]), 5,
                             f"{plat} missing install/uninstall/status/start/stop")
            self.assertIn(plat, scheduler.TRAY_BACKENDS)

    def test_poller_and_tray_labels_differ(self):
        """They are separate agents with opposite lifecycles -- periodic versus
        resident. Sharing a label would make one clobber the other."""
        self.assertNotEqual(scheduler.LABEL, scheduler.TRAY_LABEL)

    def test_tray_label_is_not_a_prefix_collision(self):
        """`com.donnish.airo.tray` contains `com.donnish.airo`, which is how a
        substring match once reported the tray's pid as the poller's."""
        self.assertTrue(scheduler.TRAY_LABEL.startswith(scheduler.LABEL),
                        "if this stops being true the warning below is moot")
        src = (ROOT / "scheduler.py").read_text(encoding="utf-8")
        self.assertIn("parts[2] == LABEL", src,
                      "status must match the label exactly, not by substring")


class TestLaunchdPlist(unittest.TestCase):
    """macOS. Generated by writing a real plist to a temp path."""

    def build(self, interval=15, here=None, with_bundle=False):
        """Run the real macos_install() and read back what it wrote.

        It used to assemble the plist dict here and assert on that, which is a
        test of its own fixture: breaking macos_install so StartInterval held
        minutes instead of seconds -- a 60x error, polling every fifteen
        seconds -- left all five of these green. launchctl and getuid are
        stubbed so the macOS backend runs on every platform, which is also
        what makes these worth running in CI at all.
        """
        tmp = Path(tempfile.mkdtemp())
        path = tmp / f"{scheduler.LABEL}.plist"
        saved = (scheduler._plist_path, scheduler.run, scheduler._uid,
                 scheduler.HERE, scheduler.data_dir)
        scheduler._plist_path = lambda: path
        scheduler.run = lambda cmd, check=False: type(
            "R", (), {"returncode": 0, "stdout": "", "stderr": ""})()
        scheduler._uid = lambda: 501
        scheduler.data_dir = lambda: tmp / "data"
        # Which branch macos_install takes depended on whether an Airo.app
        # happened to be sitting in the developer's working tree, so the same
        # test meant different things on different machines -- and on the one
        # where a bundle existed, the argv branch was never exercised at all.
        # Made an input instead.
        scheduler.HERE = Path(here) if here is not None else tmp / "project"
        scheduler.HERE.mkdir(parents=True, exist_ok=True)
        if with_bundle:
            app = scheduler.HERE / "Airo.app" / "Contents" / "MacOS"
            app.mkdir(parents=True, exist_ok=True)
            (app / "Airo").write_text("#!/bin/sh\n", encoding="utf-8")
        try:
            ok, msg = scheduler.macos_install(interval)
            self.assertTrue(ok, msg)
            return plistlib.loads(path.read_bytes())
        finally:
            (scheduler._plist_path, scheduler.run, scheduler._uid,
             scheduler.HERE, scheduler.data_dir) = saved

    def test_uses_an_interval_not_keepalive(self):
        """ARCHITECTURE 2.1: the poller runs ~2s and exits. KeepAlive would
        make it resident for nothing, and a scheduler showing no pid between
        polls is correct rather than broken."""
        d = self.build()
        self.assertIn("StartInterval", d)
        self.assertNotIn("KeepAlive", d)

    def test_interval_is_in_seconds(self):
        self.assertEqual(self.build(15)["StartInterval"], 900)
        self.assertEqual(self.build(60)["StartInterval"], 3600)

    def test_working_directory_is_the_project(self):
        """Without it the agent runs from / and every relative path breaks --
        and poller.py --doctor uses it to tell whose agent this is.

        Compared against the project the plist was built *for*, not against
        scheduler.HERE read afterwards: the harness now points HERE at a
        temporary project so both bundle branches can be exercised, and
        reading the global back gave the real checkout instead.
        """
        import tempfile as tf
        here = Path(tf.mkdtemp()) / "My Project"
        self.assertEqual(str(here), self.build(here=here)["WorkingDirectory"])

    def test_absolute_paths_only(self):
        """launchd does not inherit a shell PATH."""
        for with_bundle in (False, True):
            with self.subTest(bundle=with_bundle):
                for arg in self.build(with_bundle=with_bundle)["ProgramArguments"]:
                    self.assertTrue(Path(arg).is_absolute() or arg.startswith("--"),
                                    f"not absolute: {arg}")

    def test_without_a_bundle_it_runs_the_poller_directly(self):
        argv = self.build(with_bundle=False)["ProgramArguments"]
        self.assertTrue(argv[-2].endswith("poller.py"), argv)
        self.assertEqual("--once", argv[-1])

    def test_with_a_bundle_it_runs_that_instead(self):
        """The .app exists so macOS attributes notifications and background
        activity to "Airo" rather than to "python3"."""
        argv = self.build(with_bundle=True)["ProgramArguments"]
        self.assertEqual(1, len(argv), argv)
        # Compared as path components: asserting the string
        # "Airo.app/Contents/MacOS/Airo" fails on Windows against a plist that
        # is entirely correct, because Path renders separators per platform.
        self.assertEqual(("Airo.app", "Contents", "MacOS", "Airo"),
                         Path(argv[0]).parts[-4:], argv)


class TestSystemdUnits(unittest.TestCase):
    """Linux. Generated into a temp directory, never enabled."""

    def build(self, interval=15):
        tmp = Path(tempfile.mkdtemp())
        saved = scheduler._systemd_dir
        scheduler._systemd_dir = lambda: tmp
        saved_which = scheduler.shutil.which
        scheduler.shutil.which = lambda name: None      # no systemctl: write only
        try:
            scheduler.linux_install(interval)
            return ((tmp / f"{scheduler.SERVICE_NAME}.service").read_text(encoding="utf-8"),
                    (tmp / f"{scheduler.SERVICE_NAME}.timer").read_text(encoding="utf-8"))
        finally:
            scheduler._systemd_dir = saved
            scheduler.shutil.which = saved_which

    def test_service_is_oneshot_not_a_daemon(self):
        service, _ = self.build()
        self.assertIn("Type=oneshot", service)

    def test_service_sets_a_working_directory(self):
        """Asserted after parsing rather than as a literal.

        This used to match the exact substring `WorkingDirectory=<path>`, so
        quoting the value -- which is what stops a path with a space breaking
        the unit -- broke a test about a unit that had just got *more*
        correct. A check pinned to formatting tests the formatting.
        """
        import shlex
        service, _ = self.build()
        line = [ln for ln in service.splitlines()
                if ln.startswith("WorkingDirectory=")][0]
        self.assertEqual([str(scheduler.HERE)],
                         shlex.split(line[len("WorkingDirectory="):]))

    def test_timer_cadence_matches_the_request(self):
        _, timer = self.build(20)
        self.assertIn("OnUnitActiveSec=20min", timer)

    def test_timer_recovers_a_poll_missed_while_asleep(self):
        """Persistent=true is the systemd equivalent of the gap backfill: a
        laptop that slept through a poll runs it on wake rather than skipping."""
        _, timer = self.build()
        self.assertIn("Persistent=true", timer)

    def test_timer_is_installable(self):
        _, timer = self.build()
        self.assertIn("[Install]", timer)
        self.assertIn("WantedBy=timers.target", timer)

    def test_units_are_written_even_without_systemctl(self):
        """A container or a minimal distro may lack systemctl. Writing the
        units and saying so beats failing silently."""
        ok, msg = None, None
        tmp = Path(tempfile.mkdtemp())
        saved, saved_which = scheduler._systemd_dir, scheduler.shutil.which
        scheduler._systemd_dir = lambda: tmp
        scheduler.shutil.which = lambda name: None
        try:
            ok, msg = scheduler.linux_install(15)
        finally:
            scheduler._systemd_dir, scheduler.shutil.which = saved, saved_which
        self.assertFalse(ok)
        self.assertIn("systemctl", msg)
        self.assertTrue((tmp / f"{scheduler.SERVICE_NAME}.timer").exists())


class TestWindowsTask(unittest.TestCase):
    """Windows. The schtasks argv is built and inspected, never run."""

    def capture(self, fn, *args):
        calls = []
        saved = scheduler.run
        scheduler.run = lambda cmd, check=False: (
            calls.append(cmd),
            type("R", (), {"returncode": 0, "stdout": "", "stderr": ""})())[1]
        try:
            fn(*args)
        finally:
            scheduler.run = saved
        return calls

    def test_poller_task_uses_a_minute_interval(self):
        calls = self.capture(scheduler.windows_install, 15)
        cmd = calls[0]
        self.assertIn("/SC", cmd)
        self.assertEqual(cmd[cmd.index("/SC") + 1], "MINUTE")
        self.assertEqual(cmd[cmd.index("/MO") + 1], "15")

    def test_poller_task_is_forced_so_reinstall_works(self):
        self.assertIn("/F", self.capture(scheduler.windows_install, 15)[0])

    def test_tray_task_runs_at_logon_not_on_a_timer(self):
        """The tray is resident; scheduling it every N minutes would launch a
        second copy each time."""
        calls = self.capture(scheduler.windows_tray_install, "C:\\airo-tray.exe")
        cmd = calls[0]
        self.assertEqual(cmd[cmd.index("/SC") + 1], "ONLOGON")

    def test_poller_and_tray_use_different_task_names(self):
        poll = self.capture(scheduler.windows_install, 15)[0]
        tray = self.capture(scheduler.windows_tray_install, "x")[0]
        self.assertNotEqual(poll[poll.index("/TN") + 1],
                            tray[tray.index("/TN") + 1])


class TestTrayLifecycle(unittest.TestCase):
    def test_tray_binary_lookup_prefers_release(self):
        src = (ROOT / "scheduler.py").read_text(encoding="utf-8")
        i = src.index('for profile in (')
        self.assertLess(src.index('"release"', i), src.index('"debug"', i),
                        "a stale debug build should not shadow a release one")

    def test_install_tray_explains_how_to_build_when_missing(self):
        saved = scheduler.tray_binary
        scheduler.tray_binary = lambda: None
        try:
            ok, msg = scheduler.install_tray()
        finally:
            scheduler.tray_binary = saved
        self.assertFalse(ok)
        self.assertIn("cargo build", msg)




class TestAPathWithASpaceDoesNotBreakTheSchedule(unittest.TestCase):
    """systemd splits `ExecStart=` on whitespace.

    A project folder called "My Air Quality" therefore produces
    `ExecStart=/usr/bin/python3 /home/me/My Air Quality/poller.py --once`,
    which systemd reads as five arguments. The units install cleanly, the timer
    enables, systemctl reports success -- and every poll fails with "No such
    file or directory". Nothing surfaces it: the failure is in the journal of a
    user unit nobody thinks to read, and the symptom is simply that no readings
    arrive.

    The other two backends were immune by accident rather than by design. A
    launchd plist holds ProgramArguments as an *array*, so the shell never sees
    it, and the schtasks command was already quoting its parts. Only the one
    that built a command by string interpolation was exposed -- which is the
    general lesson, not a fact about Linux.
    """

    SPACED = "/home/someone/My Air Quality"

    def build(self, here, interval=15, tray=False, binary=None):
        import shutil as real_shutil
        tmp = Path(tempfile.mkdtemp())
        saved = (scheduler.HERE, scheduler._systemd_dir, scheduler.shutil.which)
        scheduler.HERE = Path(here)
        scheduler._systemd_dir = lambda: tmp
        scheduler.shutil.which = lambda name: None
        try:
            if tray:
                scheduler.linux_tray_install(binary or f"{here}/airo-tray")
                name = f"{scheduler.TRAY_NAME}.service"
            else:
                scheduler.linux_install(interval)
                name = f"{scheduler.SERVICE_NAME}.service"
            return (tmp / name).read_text(encoding="utf-8")
        finally:
            (scheduler.HERE, scheduler._systemd_dir,
             scheduler.shutil.which) = saved

    def exec_line(self, unit):
        """The single ExecStart value in a unit.

        One return, and it asserts there is exactly one line rather than
        taking the first: systemd treats a second ExecStart in a oneshot
        service as an additional command, so a duplicate would run the poller
        twice per tick and neither line would look wrong on its own.
        """
        lines = [ln for ln in unit.splitlines() if ln.startswith("ExecStart=")]
        self.assertEqual(1, len(lines),
                         f"expected exactly one ExecStart in:\n{unit}")
        return lines[0][len("ExecStart="):]

    def systemd_argv(self, value):
        """Split an ExecStart value the way systemd does.

        Quoted arguments are one token; unquoted whitespace separates. Written
        out rather than trusted, because the whole bug was an assumption about
        this splitting.
        """
        import shlex
        # posix=True, because a systemd unit is a POSIX artefact whatever
        # platform generated it. Verified that it leaves Windows-style
        # backslashes intact rather than eating them as escapes.
        return shlex.split(value, posix=True)

    def test_the_poller_command_survives_a_space_in_the_path(self):
        argv = self.systemd_argv(self.exec_line(self.build(self.SPACED)))
        # Asserted as a property, not as a string. Comparing against a POSIX
        # path failed on the Windows runner against a unit that was correct:
        # Path renders separators for the platform it runs on, and these units
        # are generated there only as a test convenience. What matters is that
        # the path arrived as ONE argument with its space intact.
        self.assertEqual(3, len(argv), f"the command was split apart: {argv}")
        self.assertTrue(argv[1].endswith("poller.py"), argv)
        self.assertIn("My Air Quality", argv[1],
                      f"the space did not survive: {argv}")
        self.assertEqual("--once", argv[2])

    def test_the_tray_command_does_too(self):
        argv = self.systemd_argv(self.exec_line(self.build(self.SPACED, tray=True)))
        self.assertEqual(1, len(argv), f"the tray path was split apart: {argv}")
        self.assertIn("My Air Quality", argv[0])
        self.assertTrue(argv[0].endswith("airo-tray"), argv)

    def test_the_environment_the_tray_reads_survives_it(self):
        """AIRO_HOME tells the tray where the payload is. Split in half it
        points at a directory that does not exist, and the tray comes up with
        no data and no explanation."""
        unit = self.build(self.SPACED, tray=True)
        env = [ln for ln in unit.splitlines() if ln.startswith("Environment=")]
        home = [e for e in env if "AIRO_HOME" in e][0]
        value = home[len("Environment="):]
        tokens = self.systemd_argv(value)
        self.assertEqual(1, len(tokens), f"AIRO_HOME was split: {value}")
        self.assertTrue(tokens[0].startswith("AIRO_HOME="), tokens)
        self.assertIn("My Air Quality", tokens[0], tokens)

    def test_an_ordinary_path_is_unchanged_in_meaning(self):
        """The control. Quoting everything is only a fix if the common case
        still resolves to the same argv."""
        argv = self.systemd_argv(self.exec_line(self.build("/home/someone/airo")))
        self.assertEqual(3, len(argv), argv)
        self.assertTrue(argv[1].endswith("poller.py"), argv)
        self.assertEqual("--once", argv[2])

    def test_a_percent_in_the_path_is_not_read_as_a_specifier(self):
        """`%` introduces a systemd specifier: %h is the home directory, %n
        the unit name. An unescaped one in a path expands to something else
        entirely, which is a stranger failure to debug than a space."""
        unit = self.build("/home/someone/100%25 air")
        line = self.exec_line(unit)
        self.assertNotIn("%2", line.replace("%%", ""),
                         "a bare % survived into the unit file")


class SchedulerBackendCase(unittest.TestCase):
    """Run any platform's backend on any platform.

    Every one of these functions is a shell command away from being untestable,
    which is why two thirds of this module went uncovered: on Linux only the
    linux_* branches ran, on a Mac only the macos_*. Stubbing `run` and the
    handful of platform probes makes all three exercisable everywhere, and the
    thing being asserted -- *which command, with which arguments* -- is exactly
    where the bugs are.
    """

    def setUp(self):
        self.calls = []
        self.result = {"returncode": 0, "stdout": "", "stderr": ""}
        self.tmp = Path(tempfile.mkdtemp())
        self._saved = {name: getattr(scheduler, name) for name in
                       ("run", "_uid", "_plist_path", "_systemd_dir",
                        "data_dir", "HERE")}
        self._which = scheduler.shutil.which

        def fake_run(cmd, check=False):
            self.calls.append(list(cmd))
            return type("R", (), dict(self.result))()

        scheduler.run = fake_run
        scheduler._uid = lambda: 501
        scheduler._plist_path = lambda: self.tmp / "agent.plist"
        scheduler._systemd_dir = lambda: self.tmp / "systemd"
        scheduler.data_dir = lambda: self.tmp / "data"
        scheduler.HERE = self.tmp / "project"
        scheduler.HERE.mkdir(parents=True, exist_ok=True)
        scheduler.shutil.which = lambda name: f"/usr/bin/{name}"

    def tearDown(self):
        for name, value in self._saved.items():
            setattr(scheduler, name, value)
        scheduler.shutil.which = self._which

    def argv_containing(self, needle):
        return [c for c in self.calls if any(needle in str(a) for a in c)]


class TestEveryBackendStartsAndStops(SchedulerBackendCase):
    """start/stop had no tests on any platform. They are the two commands a
    user reaches for when something looks wrong, so a silent failure here is
    found at the worst possible moment."""

    LIFECYCLE = {
        "macos": (scheduler.macos_start, scheduler.macos_stop, "launchctl"),
        "linux": (scheduler.linux_start, scheduler.linux_stop, "systemctl"),
        "windows": (scheduler.windows_start, scheduler.windows_stop, "schtasks"),
    }

    INSTALLERS = {"macos": scheduler.macos_install,
                  "linux": scheduler.linux_install,
                  "windows": scheduler.windows_install}

    def test_each_platform_drives_its_own_scheduler(self):
        for plat, (start, _, tool) in self.LIFECYCLE.items():
            with self.subTest(platform=plat):
                self.INSTALLERS[plat](15)
                self.calls.clear()
                ok, msg = start()
                self.assertTrue(ok, msg)
                self.assertTrue(self.argv_containing(tool),
                                f"{plat} start ran {self.calls}")

    def test_starting_something_never_installed_says_so(self):
        """Rather than reporting success for a schedule that does not exist,
        which is how somebody ends up believing they are collecting data."""
        ok, msg = scheduler.macos_start()
        self.assertFalse(ok)
        self.assertIn("install", msg)

    def test_stopping_does_too(self):
        for plat, (_, stop, tool) in self.LIFECYCLE.items():
            with self.subTest(platform=plat):
                self.calls.clear()
                ok, msg = stop()
                self.assertTrue(ok, msg)
                self.assertTrue(self.argv_containing(tool))

    def test_a_failing_command_is_reported_not_swallowed(self):
        """Returning (True, ...) when the scheduler refused would tell someone
        their poller is running when it is not -- and the next thing they
        notice is a hole in the record."""
        for plat in self.LIFECYCLE:
            self.INSTALLERS[plat](15)
        self.result = {"returncode": 1, "stdout": "", "stderr": "denied"}
        for plat, (start, stop, _) in self.LIFECYCLE.items():
            for name, fn in (("start", start), ("stop", stop)):
                with self.subTest(platform=plat, action=name):
                    ok, msg = fn()
                    self.assertFalse(ok, f"{plat} {name} claimed success")
                    self.assertTrue(msg.strip(), "it failed without saying why")


class TestStatusReportsWhatIsActuallyRegistered(SchedulerBackendCase):

    def test_macos_matches_the_label_exactly(self):
        """`com.donnish.airo.tray` contains `com.donnish.airo`, so a loose
        match reports the tray's pid as the poller's -- and someone reads that
        as a healthy scheduler while nothing is collecting."""
        self.result = {"returncode": 0, "stderr": "",
                       "stdout": f"1234\t0\t{scheduler.LABEL}.tray\n"}
        ok, msg = scheduler.macos_status()
        self.assertFalse(ok, f"the tray was reported as the poller: {msg}")

        self.result["stdout"] = f"999\t0\t{scheduler.LABEL}\n"
        ok, msg = scheduler.macos_status()
        self.assertTrue(ok)
        self.assertIn("999", msg)

    def test_a_pid_of_dash_between_polls_is_still_registered(self):
        """The poller runs for about two seconds and exits. No pid between
        polls is correct, and reporting it as "not running" would send someone
        chasing a fault that is the design working."""
        self.result = {"returncode": 0, "stderr": "",
                       "stdout": f"-\t0\t{scheduler.LABEL}\n"}
        ok, _ = scheduler.macos_status()
        self.assertTrue(ok)

    def test_nothing_registered_says_so(self):
        self.result = {"returncode": 0, "stdout": "", "stderr": ""}
        for status in (scheduler.macos_status, scheduler.linux_status,
                       scheduler.windows_status):
            with self.subTest(status=status.__name__):
                ok, msg = status()
                self.assertIsInstance(ok, bool)
                self.assertTrue(msg.strip())


class TestUninstallRemovesWhatInstallWrote(SchedulerBackendCase):

    def test_linux_removes_both_units_and_says_which(self):
        scheduler.linux_install(15)
        d = scheduler._systemd_dir()
        self.assertTrue((d / f"{scheduler.SERVICE_NAME}.timer").exists())
        ok, msg = scheduler.linux_uninstall()
        self.assertTrue(ok)
        self.assertFalse((d / f"{scheduler.SERVICE_NAME}.timer").exists())
        self.assertFalse((d / f"{scheduler.SERVICE_NAME}.service").exists())
        self.assertIn("timer", msg)

    def test_linux_uninstall_with_nothing_installed_is_not_an_error(self):
        """Uninstalling twice, or on a machine where install never ran, is a
        thing people do. It must not look like a failure."""
        ok, msg = scheduler.linux_uninstall()
        self.assertTrue(ok)
        self.assertIn("nothing to remove", msg)

    def test_macos_removes_the_plist(self):
        scheduler.macos_install(15)
        self.assertTrue(scheduler._plist_path().exists())
        ok, _ = scheduler.macos_uninstall()
        self.assertTrue(ok)
        self.assertFalse(scheduler._plist_path().exists())

    def test_macos_uninstall_with_no_plist_is_not_an_error(self):
        ok, _ = scheduler.macos_uninstall()
        self.assertTrue(ok)

    def test_windows_uninstall_reports_a_refusal(self):
        self.result = {"returncode": 1, "stdout": "ERROR: not found", "stderr": ""}
        ok, msg = scheduler.windows_uninstall()
        self.assertFalse(ok)
        self.assertIn("not found", msg)


class TestTheDispatchReachesEveryBackend(SchedulerBackendCase):
    """The table is the only thing connecting a platform to its implementation.

    A missing entry is a KeyError at the moment somebody installs, and a
    *wrong* entry is worse: it silently drives the wrong scheduler. Enumerated
    from BACKENDS rather than listed here, so a platform added later is in
    scope without anyone remembering to add it.
    """

    ACTIONS = ("install", "uninstall", "status", "start", "stop")

    def test_every_platform_has_a_complete_set(self):
        for plat, fns in scheduler.BACKENDS.items():
            with self.subTest(platform=plat):
                self.assertEqual(len(self.ACTIONS), len(fns))
                for name, fn in zip(self.ACTIONS, fns):
                    self.assertTrue(callable(fn), f"{plat}.{name}")

    def test_each_entry_belongs_to_its_own_platform(self):
        """A copy-paste that leaves linux_stop in the windows row runs
        systemctl on Windows, fails, and reports it as the user's problem."""
        for plat, fns in scheduler.BACKENDS.items():
            for name, fn in zip(self.ACTIONS, fns):
                with self.subTest(platform=plat, action=name):
                    self.assertTrue(
                        fn.__name__.startswith(plat),
                        f"BACKENDS[{plat!r}].{name} is {fn.__name__}")

    def test_the_front_door_routes_by_platform(self):
        for plat in scheduler.BACKENDS:
            with self.subTest(platform=plat):
                saved = scheduler.system
                scheduler.system = lambda: plat
                try:
                    self.calls.clear()
                    scheduler.status()
                    tool = {"macos": "launchctl", "linux": "systemctl",
                            "windows": "schtasks"}[plat]
                    self.assertTrue(self.argv_containing(tool),
                                    f"status() on {plat} ran {self.calls}")
                finally:
                    scheduler.system = saved

    def test_restart_stops_before_it_starts(self):
        """The other order leaves two schedules briefly, or none at all."""
        saved = scheduler.system
        scheduler.system = lambda: "linux"
        try:
            self.calls.clear()
            scheduler.restart()
        finally:
            scheduler.system = saved
        # systemctl --user <verb> <unit>: the verb is index 2, not 3. The
        # first version read the unit name and compared two identical
        # strings, which would have passed for either ordering.
        verbs = [c[2] for c in self.calls
                 if len(c) > 2 and c[0] == "systemctl"]
        self.assertEqual(["stop", "start"], verbs, self.calls)


class TestTheTrayIsInstalledResident(SchedulerBackendCase):
    """The tray is resident and starts at login, unlike the poller which wakes
    on an interval and exits. Same mechanisms, opposite lifecycle -- and
    getting that backwards means either a tray that dies at the first crash or
    a poller that never stops.

    macos_tray_install was the single largest uncovered block in the project.
    """

    def setUp(self):
        super().setUp()
        self._sleep = scheduler.time.sleep
        scheduler.time.sleep = lambda *a: None
        self.addCleanup(lambda: setattr(scheduler.time, "sleep", self._sleep))
        self.plist = self.tmp / "tray.plist"
        self._tray_plist = scheduler._tray_plist_path
        scheduler._tray_plist_path = lambda: self.plist
        self.addCleanup(lambda: setattr(scheduler, "_tray_plist_path",
                                        self._tray_plist))
        self.binary = self.tmp / "airo-tray"
        self.binary.write_text("#!/bin/sh\n", encoding="utf-8")

    def written(self):
        import plistlib
        return plistlib.loads(self.plist.read_bytes())

    def test_it_stays_resident_rather_than_running_on_a_timer(self):
        ok, msg = scheduler.macos_tray_install(self.binary)
        self.assertTrue(ok, msg)
        d = self.written()
        self.assertTrue(d["KeepAlive"],
                        "the tray would not come back after a crash")
        self.assertNotIn("StartInterval", d,
                         "a resident tray was scheduled on an interval")
        self.assertTrue(d["RunAtLoad"])

    def test_it_passes_the_tray_what_it_needs_to_find_the_payload(self):
        """AIRO_HOME is how the tray locates the Python it shells out to.
        Missing, it comes up with no data and no explanation."""
        scheduler.macos_tray_install(self.binary)
        env = self.written()["EnvironmentVariables"]
        self.assertEqual(str(scheduler.HERE), env["AIRO_HOME"])
        self.assertTrue(env["AIRO_PYTHON"])

    def test_its_logs_land_beside_the_readings_not_in_the_project(self):
        scheduler.macos_tray_install(self.binary)
        d = self.written()
        for key in ("StandardOutPath", "StandardErrorPath"):
            self.assertTrue(d[key].startswith(str(scheduler.data_dir())),
                            f"{key} writes into the project: {d[key]}")

    def test_a_bootstrap_that_loses_a_race_is_retried(self):
        """launchctl bootout is asynchronous: the label can still be
        registered for a moment after it returns, and bootstrap then fails
        with a bare "Input/output error". Without the retry this is a flaky
        install step, which reads as the tray simply not working."""
        attempts = []

        def flaky(cmd, check=False):
            attempts.append(cmd)
            if cmd[1] == "bootstrap" and len(
                    [c for c in attempts if c[1] == "bootstrap"]) < 3:
                return type("R", (), {"returncode": 5, "stdout": "",
                                      "stderr": "Input/output error"})()
            return type("R", (), {"returncode": 0, "stdout": "",
                                  "stderr": ""})()

        scheduler.run = flaky
        ok, msg = scheduler.macos_tray_install(self.binary)
        self.assertTrue(ok, msg)
        self.assertGreaterEqual(
            len([c for c in attempts if c[1] == "bootstrap"]), 2,
            "it gave up on the first failure")

    def test_a_bootstrap_that_never_succeeds_is_reported_with_its_reason(self):
        self.result = {"returncode": 5, "stdout": "", "stderr": "denied"}
        ok, msg = scheduler.macos_tray_install(self.binary)
        self.assertFalse(ok)
        self.assertIn("denied", msg, "it failed without saying why")

    def test_uninstalling_removes_the_agent_and_its_plist(self):
        scheduler.macos_tray_install(self.binary)
        self.assertTrue(self.plist.exists())
        ok, _ = scheduler.macos_tray_uninstall()
        self.assertTrue(ok)
        self.assertFalse(self.plist.exists())

    def test_uninstalling_when_nothing_is_installed_is_not_an_error(self):
        ok, _ = scheduler.macos_tray_uninstall()
        self.assertTrue(ok)

    def test_the_linux_tray_unit_is_resident_and_restarts(self):
        # Asserted rather than discarded. Capturing (ok, msg) and ignoring
        # both means the unit could be written by a call that reported
        # failure, and the test would still pass on its contents.
        ok, msg = scheduler.linux_tray_install(str(self.binary))
        self.assertTrue(ok, msg)
        unit = (scheduler._systemd_dir() /
                f"{scheduler.TRAY_NAME}.service").read_text(encoding="utf-8")
        self.assertIn("Type=simple", unit,
                      "a resident tray was declared oneshot")
        self.assertIn("Restart=on-failure", unit)
        self.assertIn("graphical-session.target", unit,
                      "a tray with no desktop session cannot draw an icon")

    def test_the_linux_tray_uninstall_removes_its_unit(self):
        scheduler.linux_tray_install(str(self.binary))
        path = scheduler._systemd_dir() / f"{scheduler.TRAY_NAME}.service"
        self.assertTrue(path.exists())
        ok, _ = scheduler.linux_tray_uninstall()
        self.assertTrue(ok)
        self.assertFalse(path.exists())

    def test_the_windows_tray_runs_at_logon_not_on_a_timer(self):
        # The last call is `schtasks /Run`, which starts it now; the schedule
        # is set by the /Create before it. Reading calls[-1] asserted against
        # the wrong command.
        scheduler.windows_tray_install(str(self.binary))
        cmd = next(c for c in self.calls if "/Create" in c)
        self.assertEqual("ONLOGON", cmd[cmd.index("/SC") + 1],
                         "scheduling a resident tray on a timer launches a "
                         "second copy every interval")

    def test_the_windows_tray_uninstall_reports_a_refusal(self):
        self.result = {"returncode": 1, "stdout": "ERROR: not found",
                       "stderr": ""}
        ok, msg = scheduler.windows_tray_uninstall()
        self.assertFalse(ok)
        self.assertTrue(msg.strip())


class TestFindingTheTrayBinary(SchedulerBackendCase):
    """Three shapes, in order of how much they are trusted. An installed app
    must win, or a stale checkout elsewhere on the machine gets launched
    instead of the app the user just installed."""

    def test_an_installed_app_wins_over_a_checkout(self):
        """Inside a bundle the binary is two directories up from the staged
        payload -- Contents/Resources/payload -> Contents/MacOS/Airo. The
        layout has to be built exactly, or this asserts nothing."""
        payload = self.tmp / "Contents" / "Resources" / "payload"
        payload.mkdir(parents=True)
        macos = self.tmp / "Contents" / "MacOS"
        macos.mkdir(parents=True)
        (macos / "Airo").write_text("x", encoding="utf-8")

        stale = payload / "tray" / "target" / "release"
        stale.mkdir(parents=True)
        (stale / scheduler.TRAY_NAME).write_text("stale", encoding="utf-8")

        scheduler.HERE = payload
        got = scheduler.tray_binary()
        self.assertEqual("Airo", Path(got).name,
                         f"a stale checkout was preferred: {got}")

    def test_release_is_preferred_over_debug(self):
        for profile in ("debug", "release"):
            d = scheduler.HERE / "tray" / "target" / profile
            d.mkdir(parents=True, exist_ok=True)
            (d / scheduler.TRAY_NAME).write_text("x", encoding="utf-8")
        got = scheduler.tray_binary()
        self.assertIn("release", str(got))

    def test_with_nothing_built_it_says_nothing_rather_than_guessing(self):
        self.assertIsNone(scheduler.tray_binary())


class TestTheCommandLineDispatch(SchedulerBackendCase):
    """`scheduler.py <action>` — the front door, and the least-covered part of
    the least-covered module.

    What it does is route an action to a backend and turn a (ok, message) pair
    into an exit code. Both halves matter to somebody running it from a
    terminal or a launchd job: a wrong route silently drives the wrong
    scheduler, and a wrong exit code makes a failed install look successful to
    anything checking `$?`.
    """

    #: Enumerated from the parser itself rather than written out here, so an
    #: action added later is in scope without anyone remembering. The listed
    #: version of this check is exactly how a project ends up with a command
    #: that has no test.
    def actions(self):
        import argparse
        for action in getattr(scheduler, "main").__doc__ or "":
            pass
        src = (ROOT / "scheduler.py").read_text(encoding="utf-8")
        import re
        m = re.search(r'choices=\((.*?)\)', src, re.S)
        self.assertTrue(m, "the action list has moved or changed shape")
        return re.findall(r'"([a-z-]+)"', m.group(1))

    def run_main(self, *argv):
        import contextlib
        import io
        out = io.StringIO()
        saved = sys.argv
        sys.argv = ["scheduler.py", *argv]
        try:
            with contextlib.redirect_stdout(out), contextlib.redirect_stderr(out):
                code = scheduler.main()
        except SystemExit as e:
            code = e.code if isinstance(e.code, int) else 1
        finally:
            sys.argv = saved
        return code, out.getvalue()

    #: Which function each action must reach. The dispatch is an if/elif
    #: chain ending in a bare `else: status()`, so an action the chain does
    #: not handle does not fail -- it quietly reports status instead, and an
    #: install that never happened looks like a healthy one.
    ROUTES = {
        "install": "install", "uninstall": "uninstall", "start": "start",
        "stop": "stop", "restart": "restart", "status": "status",
        "install-tray": "install_tray", "uninstall-tray": "uninstall_tray",
    }

    def test_every_action_reaches_its_own_backend(self):
        """Asserted on which function ran, not on whether anything printed.

        The first version checked that each action "said something", which is
        true of a fall-through as well -- it passed with `uninstall-tray`
        routed to `status`.
        """
        actions = self.actions()
        self.assertEqual(sorted(self.ROUTES), sorted(actions),
                         "the parser's actions and this map have diverged")

        for action in actions:
            with self.subTest(action=action):
                ran = []
                saved = {}
                for name in set(self.ROUTES.values()):
                    saved[name] = getattr(scheduler, name)
                    setattr(scheduler, name, (
                        lambda n: lambda *a, **kw: (ran.append(n), (True, n))[1]
                    )(name))
                try:
                    code, said = self.run_main(action)
                finally:
                    for name, fn in saved.items():
                        setattr(scheduler, name, fn)
                self.assertEqual([self.ROUTES[action]], ran,
                                 f"{action} ran {ran} instead of "
                                 f"{self.ROUTES[action]}")
                self.assertEqual(0, code, said)

    def test_it_names_the_platform_it_is_acting_on(self):
        """Half the support questions about this file are somebody on one
        platform reading instructions for another."""
        _, said = self.run_main("status")
        self.assertIn(scheduler.system(), said)

    def test_a_failure_exits_nonzero(self):
        """launchd, systemd and Task Scheduler all read the exit code. An
        install that failed but exited 0 is recorded as healthy."""
        self.result = {"returncode": 1, "stdout": "", "stderr": "denied"}
        code, said = self.run_main("start")
        self.assertEqual(1, code, said)

    def test_success_exits_zero(self):
        for action in ("install", "start", "stop"):
            with self.subTest(action=action):
                self.INSTALLERS = None
                code, said = self.run_main(action)
                self.assertEqual(0, code, said)

    def test_the_interval_reaches_the_backend(self):
        """`--interval 30` that silently installs a 15-minute schedule is the
        kind of thing nobody notices for a month."""
        self.run_main("install", "--interval", "30")
        written = (self.tmp / "systemd" / f"{scheduler.SERVICE_NAME}.timer")
        plist = self.tmp / "agent.plist"
        if written.exists():
            self.assertIn("30min", written.read_text(encoding="utf-8"))
        elif plist.exists():
            import plistlib
            self.assertEqual(1800, plistlib.loads(plist.read_bytes())["StartInterval"])
        else:
            self.assertTrue(any("30" in " ".join(map(str, c)) for c in self.calls),
                            f"the interval never reached the backend: {self.calls}")

    def test_status_reports_the_tray_binary_or_how_to_build_it(self):
        """Status is diagnostic. "not built" with the command to fix it beats
        an empty line that reads as a missing feature."""
        _, said = self.run_main("status")
        self.assertTrue("tray binary:" in said, said)
        self.assertTrue("cargo build" in said or "/" in said.split("tray binary:")[1],
                        said)

    def test_an_unknown_action_is_refused_by_the_parser(self):
        """argparse exits 2 rather than falling through to status, which would
        report on a scheduler the user did not ask about."""
        code, _ = self.run_main("frobnicate")
        self.assertEqual(2, code)


class TestWhereTheDataDirComesFrom(unittest.TestCase):
    """Scheduler log paths must land beside the readings, not inside the
    project — or a migrated install writes its logs to a folder nothing else
    reads, and the person looking for them finds an empty file."""

    def test_it_asks_poller_rather_than_assuming(self):
        import poller
        self.assertEqual(Path(poller.DATA), scheduler.data_dir())

    def refuse_poller(self):
        """Run data_dir() with `import poller` broken. Returns (path, stderr)."""
        import builtins
        import contextlib
        import io
        import sys as _sys
        real_import = builtins.__import__

        def refuse(name, *a, **kw):
            if name == "poller":
                raise ImportError("poller is broken")
            return real_import(name, *a, **kw)

        saved = _sys.modules.pop("poller", None)
        builtins.__import__ = refuse
        err = io.StringIO()
        try:
            with contextlib.redirect_stderr(err):
                got = scheduler.data_dir()
        finally:
            builtins.__import__ = real_import
            if saved is not None:
                _sys.modules["poller"] = saved
        return got, err.getvalue()

    def test_it_falls_back_rather_than_raising_when_poller_cannot_load(self):
        """The fallback exists because scheduler.py has to work well enough to
        *uninstall* even when the rest of the project is broken -- which is
        exactly when somebody reaches for it."""
        got, _ = self.refuse_poller()
        self.assertIsInstance(got, Path)

    def test_the_fallback_is_the_real_default_not_the_project_folder(self):
        """It answered `$PROJECT/data`, which is the one path that is
        certainly wrong.

        CONVENTIONS rule 2a records that shape by name: hardcoding
        `$PROJECT/data` rather than asking poller created a stray empty
        database beside the real one and reported zero rows for a working
        install. Offering it as the *fallback* is the same mistake wearing a
        safety label -- a scheduler that cannot reach poller then writes its
        logs into the checkout, where nothing else looks.
        """
        got, _ = self.refuse_poller()
        self.assertNotEqual(scheduler.HERE / "data", got,
                            "the fallback still points inside the project")
        self.assertEqual(Path.home() / ".airo" / "data", got)

    def test_the_fallback_honours_AIRO_DATA_as_poller_does(self):
        elsewhere = Path(tempfile.gettempdir()) / "airo-fallback-probe"
        saved = os.environ.get("AIRO_DATA")
        os.environ["AIRO_DATA"] = str(elsewhere)
        try:
            got, _ = self.refuse_poller()
        finally:
            if saved is None:
                os.environ.pop("AIRO_DATA", None)
            else:
                os.environ["AIRO_DATA"] = saved
        self.assertEqual(elsewhere, got)

    def test_the_fallback_says_it_is_guessing(self):
        """A fallback that returns a plausible path in silence is how somebody
        spends an afternoon looking for logs that were written elsewhere."""
        got, said = self.refuse_poller()
        self.assertIn("poller", said)
        self.assertIn(str(got), said)


class TestATestCannotUninstallTheDevelopersAgent(unittest.TestCase):
    """The fourth route into the developer's own install, and the one that
    survived the first three being closed.

    `homeguard` redirects the paths and HOME. launchd cannot be redirected:
    `launchctl` addresses agents as `gui/<uid>/<label>`, keyed on the uid and
    a fixed label. So a subprocess running under a temp HOME deletes a plist
    that was never there and unloads the *real* agent belonging to the login
    session.

    This is how the developer's poller stopped. The evidence was unhelpful in
    every direction: the plists sat untouched on disk, `launchctl list` showed
    nothing, and the last line in the log is a clean successful poll. Nothing
    failed, so nothing was reported.
    """

    def redirect_home(self, to):
        """Redirect whichever variable this platform actually reads.

        Windows uses USERPROFILE, not HOME — a test setting only one runs
        against the real home directory on the other platform, which is a trap
        already written down in CONVENTIONS and one I walked into here.
        """
        for name in ("HOME", "USERPROFILE"):
            saved = os.environ.get(name)
            os.environ[name] = to
            self.addCleanup(
                lambda n=name, v=saved: os.environ.__setitem__(n, v) if v
                else os.environ.pop(n, None))

    def test_a_redirected_home_does_not_own_the_session(self):
        self.redirect_home(os.path.join(tempfile.gettempdir(), "not-a-home"))
        self.assertFalse(scheduler.owns_the_live_session())

    def test_the_real_home_does_own_it(self):
        """The other half. A guard that refuses everything protects nothing,
        because the first person it inconveniences turns it off.

        The real home comes from `homeguard`, which captured it at import
        before any redirection — asking the environment here would return the
        redirected one, since this whole suite runs under it. That the plain
        call above returns False during a test run *is the guard working*, and
        was the first result this test gave.
        """
        self.redirect_home(str(Path(REAL_AIRO_HOME).parent))
        self.assertTrue(scheduler.owns_the_live_session(),
                        "the ordinary case is being refused")

    def test_every_session_manager_is_guarded_not_just_launchd(self):
        """Enumerated from SESSION_MANAGERS rather than checked for launchctl
        alone. systemd's `--user` units and Task Scheduler are addressed the
        same way — by the session, not by HOME — so a Linux or Windows test
        doing what the macOS one did would have exactly the same effect there,
        and nobody would connect the two.
        """
        self.redirect_home(os.path.join(tempfile.gettempdir(), "not-a-home"))
        # Named literally, then enumerated. Enumerating alone was not enough:
        # narrowing SESSION_MANAGERS to ("launchctl",) shrank the loop with it
        # and nothing went red — "enumerate, don't list" protects against
        # something being *added* and missed, not against the enumeration
        # itself being cut. Which tools address a session is a claim about the
        # world, so it is written down; the behaviour is then checked over
        # whatever the module actually carries.
        for required in ("launchctl", "systemctl", "schtasks"):
            self.assertIn(required, scheduler.SESSION_MANAGERS,
                          f"{required} addresses the session by uid and is "
                          f"no longer guarded")
        for manager in scheduler.SESSION_MANAGERS:
            result = scheduler.run([manager, "--version"])
            self.assertEqual(1, result.returncode, manager)
            self.assertIn("logged-in session", result.stderr, manager)

    def test_an_ordinary_command_is_not_blocked_by_the_guard(self):
        """The guard is about sessions, not about subprocesses. Blocking
        everything under a redirected HOME would break the bundle tests, which
        legitimately run the shipped poller that way."""
        self.redirect_home(os.path.join(tempfile.gettempdir(), "not-a-home"))
        self.assertEqual(0, scheduler.run(["true"]).returncode)

    def test_the_guarded_runner_refuses_and_says_why(self):
        self.redirect_home(os.path.join(tempfile.gettempdir(), "not-a-home"))

        result = scheduler.run(["launchctl", "list"])
        self.assertNotEqual(0, result.returncode)
        self.assertIn("logged-in session", result.stderr,
                      "the refusal does not say what it refused or why")

    @unittest.skipUnless(hasattr(os, "getuid"),
                         "macos_stop() addresses launchd by uid, and Windows "
                         "has no getuid; the guard itself is covered on every "
                         "platform by the tests above")
    def test_uninstall_under_a_redirected_home_leaves_the_session_alone(self):
        """The end-to-end shape of it: the operation reports its failure
        rather than silently reaching across."""
        self.redirect_home(os.path.join(tempfile.gettempdir(), "not-a-home"))

        calls = []
        real = subprocess.run
        subprocess.run = lambda args, *a, **kw: (
            calls.append(args) or real(["true"], *a, **kw))
        self.addCleanup(lambda: setattr(subprocess, "run", real))

        scheduler.macos_stop()
        self.assertEqual(
            [], [c for c in calls if c and c[0] == "launchctl"],
            "launchctl reached a subprocess despite the redirected HOME")

    def test_no_session_manager_reaches_a_subprocess_from_this_suite(self):
        """The floor underneath the product's own guard, asserted rather than
        assumed.

        `scheduler.run()` refuses these while HOME is redirected, and every
        check above is about that refusal. This one goes around it: it calls
        `subprocess.run` directly, which is what a new suite does without
        meaning anything by it, and which no amount of care inside
        `scheduler.run` can cover.

        A guard nobody has watched fail is not evidence, so
        `tools/faults/guards.json` removes the installation and expects this to
        go red. `launchctl list` is a read, deliberately: while the guard is
        disabled the command really does run.
        """
        guard = schedguard.current()
        self.assertIsNotNone(guard, "the session guard is not installed")
        result = subprocess.run(["launchctl", "list"], capture_output=True,
                                text=True)
        self.assertEqual(1, result.returncode,
                         "a session manager reached a real subprocess")
        self.assertIn("logged-in session", result.stderr)
        self.assertTrue(guard.attempts, "the attempt was not recorded")

    def without_pwd(self):
        """Make `import pwd` fail, so the Windows branch runs on any machine.

        Both Windows behaviours below were green on macOS with the bug
        present, because `pwd` imports fine here and the fallback never ran.
        That is the shape this project keeps being caught by — a
        platform-specific symptom tested only on the platform that does not
        have it — and the stated remedy is to add a check that is not
        platform-specific. This is that check.
        """
        import builtins
        real_import = builtins.__import__

        def refuse(name, *args, **kwargs):
            if name == "pwd":
                raise ImportError("no pwd module on this platform")
            return real_import(name, *args, **kwargs)

        builtins.__import__ = refuse
        self.addCleanup(lambda: setattr(builtins, "__import__", real_import))

    def test_without_a_passwd_database_a_redirected_home_is_still_caught(self):
        """Windows has no passwd database, and `expanduser` reads the very
        variables under test, so it cannot be the reference. Returning True
        there was the first version, and it made the guard do nothing on the
        platform where Task Scheduler *is* the session manager — the exact
        failure this exists to prevent, on a different OS."""
        self.without_pwd()
        self.redirect_home(os.path.join(tempfile.gettempdir(), "not-a-home"))
        self.assertFalse(scheduler.owns_the_live_session())
        self.assertEqual(1, scheduler.run(["schtasks", "/query"]).returncode,
                         "Task Scheduler was reachable from a redirected home")

    def test_without_a_passwd_database_the_real_home_still_owns_it(self):
        self.without_pwd()
        self.redirect_home(str(scheduler._HOME_AT_IMPORT))
        self.assertTrue(scheduler.owns_the_live_session())

    def test_the_windows_variable_is_read_not_just_home(self):
        """`USERPROFILE`, not `HOME`. A test setting only one runs against the
        real home directory on the other platform — a trap already written
        down in CONVENTIONS, and one this guard walked into."""
        self.without_pwd()
        for name in ("HOME", "USERPROFILE"):
            saved = os.environ.get(name)
            os.environ.pop(name, None)
            self.addCleanup(
                lambda n=name, v=saved: os.environ.__setitem__(n, v) if v
                else os.environ.pop(n, None))
        os.environ["USERPROFILE"] = os.path.join(tempfile.gettempdir(),
                                                 "not-a-home")
        self.assertFalse(scheduler.owns_the_live_session(),
                         "USERPROFILE is ignored, so Windows is unguarded")


if __name__ == "__main__":
    unittest.main(verbosity=2)
